CLASS zcl_00_abapcloud_7516 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_00_ABAPCLOUD_7516 IMPLEMENTATION.


METHOD if_oo_adt_classrun~main.
   out->write( 'This es my fisrts class'  ).

 ENDMETHOD.
ENDCLASS.
